"""Builds the public, multi-user edition into public/ .

The app files are copied verbatim from the repo root — the public edition is the
same app, not a fork — and only cloud-config.js is written fresh, carrying the
Supabase project URL and anon key. That file is what puts the app in cloud mode,
which is why it exists in public/ and nowhere else: the personal app at the repo
root keeps the inert copy and behaves exactly as it always has.

    python supabase/make-public.py --url https://xxxx.supabase.co --key eyJ...

Both values are safe to publish: the anon key can only ever reach the rows of
whoever is signed in, which the database enforces (supabase/schema.sql). The
service_role key must never appear here or anywhere in this repo.

Re-run it after any change to app.html / m.html to keep the two in step.
"""
import argparse
import pathlib
import re
import shutil

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "public"

# Everything the app needs at runtime. cloud-config.js is deliberately absent —
# it is generated below.
FILES = ["app.html", "m.html", "index.html", "cloud.js", "cloud-ui.js",
         "manifest.webmanifest", "icon-180.png", "icon-192.png", "icon-512.png",
         "favicon-32.png"]

CONFIG = """/* The public edition runs in cloud mode: accounts, and per-user storage.
 *
 * Both values below are public by design. The anon key only ever reaches the
 * rows of the signed-in user, which the database enforces through row level
 * security — see supabase/schema.sql. The service_role key is NOT here and must
 * never be.
 *
 * Generated by supabase/make-public.py — edit that, not this.
 */
window.SB_CLOUD_CONFIG = {
  url: '%(url)s',
  anonKey: '%(key)s'
};
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", required=True, help="https://YOUR-PROJECT.supabase.co")
    ap.add_argument("--key", required=True, help="the anon / publishable key (starts eyJ)")
    args = ap.parse_args()

    url = args.url.rstrip("/")
    if not re.fullmatch(r"https://[a-z0-9-]+\.supabase\.(co|in)", url):
        raise SystemExit(f"That does not look like a project URL: {url}")
    if not args.key.startswith("eyJ"):
        raise SystemExit("That does not look like the anon key (it should start with 'eyJ').")
    # A service_role key would hand every visitor the keys to everyone's data.
    if "service_role" in args.key or '"role":"service_role"' in args.key:
        raise SystemExit("That is the service_role key. Use the anon / publishable key.")

    OUT.mkdir(exist_ok=True)
    for name in FILES:
        src = REPO / name
        if not src.exists():
            raise SystemExit(f"Missing {name} — run this from the repo.")
        shutil.copy2(src, OUT / name)

    (OUT / "cloud-config.js").write_text(CONFIG % {"url": url, "key": args.key}, encoding="utf-8")

    print(f"public/ built: {len(FILES) + 1} files")
    print(f"  cloud mode on, project {url}")
    print("  deploy: commit public/ and open https://<you>.github.io/<repo>/public/")


if __name__ == "__main__":
    main()
